# Generated by Django 2.1.7 on 2019-07-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enthnicity', models.CharField(max_length=10)),
                ('imagePath', models.CharField(max_length=300)),
            ],
        ),
    ]
