# Generated by Django 2.1.7 on 2019-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
