# Generated by Django 2.1.7 on 2019-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190706_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='enthnicity',
            field=models.CharField(max_length=200),
        ),
    ]
