# Generated by Django 2.1.7 on 2019-07-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20190707_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecontent',
            old_name='enthnicity',
            new_name='ethnicity',
        ),
    ]
